FROM mcr.microsoft.com/devcontainers/javascript-node:16

# Install Expo CLI globally
RUN npm install -g expo-cli

WORKDIR /workspaces/PotofGold


# Expose Expo ports
EXPOSE 19000 19001 19002

FROM mcr.microsoft.com/devcontainers/javascript-node:16

RUN npm install -g expo-cli

WORKDIR /workspaces/PotofGold

EXPOSE 19000 19001 19002
